### ISSUE TITLE
Studio tecnologie di sviluppo [python + txtai]

### ISSUE THREAD

**Issue by Rikicavaz77** [Argo-swe/ChatSQL#2]

**Comment by CristoMarco** [comment]
![photo1714125540](https://github.com/Argo-swe/ChatSQL/assets/162626105/49540927-db50-4bdb-87b3-d21ba1e23d95)
![photo1714125540(1)](https://github.com/Argo-swe/ChatSQL/assets/162626105/aded458f-dffe-4b72-bd58-dc7d12beda82)
![photo1714125540(2)](https://github.com/Argo-swe/ChatSQL/assets/162626105/c043ac0c-ac9d-4db6-97de-58effbfdb27f)
