### ISSUE TITLE
Dizionario dati + composizione prompt

### ISSUE THREAD

**Issue by Rikicavaz77** [Argo-swe/ChatSQL#3]
Lasciare un commento con il lavoro svolto o, eventualmente, caricare i file prodotti.

**Comment by LewentalDigital** [comment]
Progettazione dizionario dati e prompt sono documentate qui: <a href="https://docs.google.com/document/d/17c-LhXLpI8vcefLVe9gEW_6qS8unK7-gd-D_pkLZEzA/edit">Documento progettazione<a>

[ARGO-6]

[ARGO-6]: https://argo-swe-2.atlassian.net/browse/ARGO-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
