### ISSUE TITLE
Errore docker compose [entrypoint]

### ISSUE THREAD

**Issue by Rikicavaz77** [Argo-swe/ChatSQL#48]

**Comment by stoccotommaso02** [comment]
# Problema
- Sistema operativo: Windows
L'avvio dei container con entrypoint non era possibile e causava problemi descritti così:
![immagine](https://github.com/Argo-swe/ChatSQL/assets/78268348/4780e087-bb00-4cbd-98c9-68eaf94c05b7)
Tuttavia nei rispettivi Dockerfile gli script erano importati correttamente, ed erano correttamente resi eseguibili attraverso `chmod`.
---
# Soluzione
Le immagini Docker non erano in grado di visualizzare gli script entrypoint in quanto il formato end-of-line di Windows (`CRLF`) non è ben accetto da script Shell Linux-like, che utilizzano `LF`. Fortunatamente il fix è molto semplice e consiste nel modificare, all'interno del proprio editor, l'impostazione apposita.
